version: 2.1
orbs:
  gor: hubci/goreleaser@2.0
workflows:
  main-wf:
    jobs:
      - test
      - gor/release:
          version: 1.7.0
          go-version: '1.18'
          dry-run: true
jobs:
  test:
    docker:
      - image: cimg/go:1.18
    steps:
      - checkout
      - run:
        name: Run Tests
        command: go test -v