version: 2.1

orbs:
  go: circleci/go@1.9.0

jobs:
  build:
    docker:
      - image: circleci/golang:1.14.6
    steps:
      - checkout
      - run:
          name: Run tests
          command: go test -v
      - run:
          name: Database Setup
          command: |
            bundle exec rake db:create
            bundle exec rake db:structure:load
      - run:
          name: Fixture Setup
          command: ioutil.ReadFile("fixture/fixture.json")
          
      - run:
          name: Migration Setup
          command: migrate -source file://./migrations/users/ -database 'mysql://root:Shinya0023@tcp(127.0.0.1:3306)/yamamoto' up
            

 
  